import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Google_Client } from "@/constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode,
}>) {

  return (
    <html lang="en">
      <GoogleOAuthProvider clientId={Google_Client}>
        <body className={inter.className}>
          {children}
        </body>
      </GoogleOAuthProvider>
    </html>
  );
}
